### ISSUE TITLE
Player can hide an image by shooting a fire arrow at the image.

### ISSUE THREAD

**Issue by Ecilpse** [josemmo/yamipa#104]
![image](https://github.com/josemmo/yamipa/assets/25452835/94119591-14dc-472f-ad70-a1e46f68b375)

Player can hide an image by shooting a fire arrow at the image.
Other players feel uncomfortable with these issues. can it fixed?

**Comment by josemmo** [comment]
Well, for better or worse, that's just how the game works. I prefer to avoid changing the behavior of existing game mechanics to not break other plugins or game worlds as some players might rely on arrows behaving like that.

There's a really simple solution, though: just **remove the blocks behing the image**. The image will still be rendered and there will be no block for arrows to attach to.

**Comment by Ecilpse** [comment]
> Well, for better or worse, that's just how the game works. I prefer to avoid changing the behavior of existing game mechanics to not break other plugins or game worlds as some players might rely on arrows behaving like that.
> 
> There's a really simple solution, though: just **remove the blocks behing the image**. The image will still be rendered and there will be no block for arrows to attach to.

![image](https://github.com/josemmo/yamipa/assets/25452835/d72db001-bc73-4743-8337-1758644cc673)
arrow fire was still attacted itemframe although block was not behind.

**Comment by josemmo** [comment]
Well, there's not much we can do in Yamipa. Because the image is _not really there_ in the world, the Minecraft server will calculate the position of the arrow being thrown in a different place:

![arrow](https://github.com/josemmo/yamipa/assets/4470267/2ff30e4e-0d67-4907-bbcc-be4058fa20f2)

As such, Yamipa (the plugin) will not get the event for an arrow hitting the image.

My advice would be to use a different plugin to prevent the usage of bows in a particular world area.
