### ISSUE TITLE
v1.2.12 - Players can destroy images

### ISSUE THREAD

**Issue by vYuri** [josemmo/yamipa#109]
For some reason players can remove the images that are placed. I haven't found a way to fix that tho. WorldGuard regions are not working for yamipa

**Comment by josemmo** [comment]
Hello @vYuri,

What do you mean by "players can remove the images that are placed"? That's the expected behavior unless you configure Yamipa differently.

- What version of Paper are you using? e.g., MC 1.20.2 build 260
- What ProtocolLib version are you using? e.g., v5.1.0
- On what version of Yamipa does this bug occur? e.g., v1.2.12
- Does Yamipa raise any warning or error entries in the server logs? If so, paste them in this thread.

**Comment by vYuri** [comment]
Hello!

I am using:

- Paper 1.20.2 BUILD 318
- ProtocolLib 5.1.1-SNAPSHOT-673
- Yamipa 1.2.12

There are no console errors or entity message errors on console.

If so, how is that I can change the configuration for players to not break the images/gifs? I haven't found a way in the configuration file. Thanks!

**Comment by josemmo** [comment]
The simplest solution is to not let players use the "remove" command. You can use [permissions](https://github.com/josemmo/yamipa#permissions) for that matter. If you read the documentation, you'll see there's even a special permission (`yamipa.command.remove.own`) to let players remove only the images they've placed.

If you use WorldGuard or similar, check out the [Protecting areas](https://github.com/josemmo/yamipa#protecting-areas) section of the documention.

If you're handing out image items instead of letting players use commands, and don't want them to remove images once placed, you can remove the "REMO" flag when generating the image items as explained in the [documentation](https://github.com/josemmo/yamipa#flags).
