### ISSUE TITLE
Images don't load when player approaches in a custom vehicle

### ISSUE THREAD

**Issue by Kinboise** [josemmo/yamipa#115]
I'm aware that #78 has been fixed for minecarts and other vanilla rideable entities. But it still doesn't work with plugin-added vehicles. Is it possible to just detect the player?

**Comment by josemmo** [comment]
Hello, @Kinboise!

It depends on how the plugin introduces custom vehicles. Which plugin are you using?

**Comment by Kinboise** [comment]
I'm using Citizens and MTVehicles. As far as I know, Citizens is probably using fake entity for its NPCs, and MTVehicles uses armor stands for its cars.

**Comment by josemmo** [comment]
So, the reason Yamipa cannot track the player when in a vehicle from MTVehicles is because the latter does not trigger neither the `PlayerMoveEvent` nor `VehicleMoveEvent`. Without that, Yamipa (or any plugin, for that matter) cannot know the player moved.

Honestly, I don't how to proceed here 🤷‍♂️
I'm not even sure whether this is something MTVehicles should fix as it's related to Bukkit:

- https://hub.spigotmc.org/jira/browse/SPIGOT-3770
- https://github.com/PaperMC/Paper/issues/4041

**Comment by josemmo** [comment]
Closed due to inactivity.
