### ISSUE TITLE
Cant load or download images

### ISSUE THREAD

**Issue by Mentembentem** [josemmo/yamipa#2]
When putting images into the image folder or trying to download an image the commands dont work.

**Comment by atesz19** [comment]
Its not my plugin, but its working for me fine...
Do you have an updated protocol lib plugin installed?

**Comment by atesz19** [comment]
and if you have MultiverseCore you should use the latest build https://github.com/josemmo/yamipa/releases/tag/v1.0.4-SNAPSHOT
becouse the spigot one (1.0.3) dont work on multiverse worlds

**Comment by josemmo** [comment]
Hi, @Mentembentem!

Could you give more details on how to reproduce the error? Such as what server are you using (Spigot, PaperMC, Bukkit), plugins you have installed, the latest server log for when Yamipa failed, expected behavior vs achieved result, etc.

As @atesz19 said, try the [latest snapshot](https://github.com/josemmo/yamipa/releases/tag/v1.0.4-SNAPSHOT) if you haven't already and let us know if the bug keeps happening.

**Comment by Mentembentem** [comment]
Hey guys thanks for the fast reply, I already fixed it a friend of mine
helped me out.

Nice plugin!
Op vr 9 apr. 2021 18:21 schreef José Miguel Moreno ***@***.***

**Comment by josemmo** [comment]
Glad to hear! I'm closing this issue.
