### ISSUE TITLE
Couple of Suggestions

### ISSUE THREAD

**Issue by Catches** [josemmo/yamipa#31]
I have a few suggestions, can you make the image automatically format to its size? So we don't have to enter the diameters? Also the plugin is incredible, but ImageOnMap is much easier to use, could you more simple and easier for the players? Like /image <url>

**Comment by josemmo** [comment]
Hello @Catches,

> can you make the image automatically format to its size? So we don't have to enter the diameters?

Not sure how to implement this, Yamipa needs to know what dimensions you want an image to have.

---

> could you more simple and easier for the players? Like /image

How would that work? Like a UI dialog, you mean?

**Comment by Catches** [comment]
ImageOnMap basically does all of this, you can check it out; https://www.spigotmc.org/resources/imageonmap.26585/

**Comment by josemmo** [comment]
I've looked at the plugin page and, if I understood correctly, there's no resizing option in ImageOnMap, right? So the final size of the placed image will depend on the dimensions of the original image file.

In Yamipa, the original image dimensions are only used to get the image ratio, you can place the image in whatever size you want. This is why you need to tell Yamipa at least the image width in blocks when placing an image (`/image place <filename> <width>`).

Would you mind explaining what feature would you like to see in Yamipa? Because I don't see what can be done to simplify the command.

**Comment by Catches** [comment]
There is a resizing option, it's /tomap <url> resize. Yeah, I'm saying you on top of a automatic resizing thing, you could also add custom dimensions. For example, the resize will make it viewable when holding the map in the hand, while the regular command would just make it resize automatically but able to be like put in frames.

Just like a simple /image <url> command would be nice for end-users.

**Comment by josemmo** [comment]
I still don't get how to do the auto-resize thing, what should be the default dimension of an image? Is it really that painful to specify the width (and optionally height) of an image before placing it?

Anyway, if you don't want your players to use commands in your server you can always use image items, which feel like any other vanilla in-game item and can places images when right-clicking surfaces. You have more info on how to use the `/image give` command to generate these items in the [documentation](https://github.com/josemmo/yamipa#usage) page.
