### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by halofreak894** [josemmo/yamipa#36]
Hi, loving the plugin so far! Everything works so smoothly! I was wondering if a feature could be added to start, stop, or even pause a gif that is playing on the screen? Such as:
/image start <filename>
/image pause <filename>
/image stop <filename>
If these could be run by command blocks that'd also be extremely helpful, this would just help for what I want to create working screens for. Also, not sure if this is possible, but what are the changes of being able to put an actual video on the screen, since they're smaller in size than a gif and can be longer. Just an idea, and was wondering if any of these were possible.

Thank you so much!

**Comment by josemmo** [comment]
Hi, @halofreak894!

To add commands for starting/stopping animated images, Yamipa will need to have some ID generation system to identify placed images so that you could call `/image pause <image-id>`. Maybe some kind of redstone integration will suffice? I'm thinking powering a block to pause an image from animating, although it might not possible if it severely impacts performance.

Regarding videos, that won't be possible. Minecraft is not in any way designed to render images, it's almost magic this plugin works. For every frame your GIF file has, it takes a decent amount of RAM in your server plus uses bandwidth when sending that data to clients. A video will for sure crash the server at some point and saturate the network with traffic.

**Comment by josemmo** [comment]
Closed due to inactivity.
