### ISSUE TITLE
Unable to remove image with ANIM flag

### ISSUE THREAD

**Issue by wtlgo** [josemmo/yamipa#54]
The problem is in the description. The command I use to get the image is

```
/yamipa give MikChan test.gif 1 4 2 REMO,ANIM
```

If I place it, it is impossible to remove it unless you use the command `/yamipa remove`.

**Comment by josemmo** [comment]
Hello @wtlgo,

That's the intended behavior. You're overwriting the default "give" command flags, so effectively the only flag your image item has is "ANIM" (animatable) because it's the last one you pass.

You don't need to pass any flags to the command, just use it like this:
```
/yamipa give MikChan test.gif 1 4 2
```

Please, read the [documentation regarding flags](https://github.com/josemmo/yamipa#flags).
