### ISSUE TITLE
Color inaccuracy for green shades.

### ISSUE THREAD

**Issue by alekso56** [josemmo/yamipa#7]
Lighter green shades are interpreted as blue shades. 
![greenshades](https://user-images.githubusercontent.com/676987/127714059-b02f225f-a6b8-425f-aa51-687f231b1f6f.png)
![0axYYcl](https://user-images.githubusercontent.com/676987/127714124-0145865f-7034-4b25-b822-11bca39dc045.png)

**Comment by josemmo** [comment]
Yup, that's the expected behavior.

The way Yamipa renders images in your Minecraft world is by using maps and item frames. For better or worse, the [available color palette](https://minecraft.fandom.com/wiki/Formatting_codes#Color_codes) for maps is quite limited (not your typical 24-bit color depth), so Yamipa tries to match image colors as close as possible, leading to situations like this:

![Color spectrum](https://user-images.githubusercontent.com/4470267/127736631-2e8dd338-2ea4-4a9e-b50c-96e428780d7d.png)

One possible workaround for this could be [dithering](https://en.wikipedia.org/wiki/Dither). If I have the time and energy I'll experiment with it and maybe add it to Yamipa.
