### ISSUE TITLE
it will not work at all

### ISSUE THREAD

**Issue by Moxie15** [josemmo/yamipa#71]
so have every thing needed and i have a pic but when i run the com it does nothing 
says nothing does nothing 

![Screenshot 2022-12-20 194430](https://user-images.githubusercontent.com/88121853/208800954-f0be7a8d-6eab-4bfe-b070-ae44d6af2649.png)
![Screenshot 2022-12-20 194451](https://user-images.githubusercontent.com/88121853/208800979-9028e466-9a7a-4113-99d1-fc58d90cb129.png)

**Comment by Moxie15** [comment]
i have tired naming it gay.png and jpg and it still didnt work

**Comment by josemmo** [comment]
First thing, I'm guessing your command should end with `+GLOW` instead of `GLOW`. Check the [documentation](https://github.com/josemmo/yamipa#flags) for a detailed explanation.

And now, the usual questions:

- What server are you running? SpigotMC, Bukkit, PaperMC, etc.
- What Minecraft version are you on? 1.19.2, 1.19.3, etc.
- What version of ProtocolLib are you using? 4.8.0, 5.0.0-SNAPSHOT-b608, etc.
- What server logs are you getting when running the command? Make sure to [enable "verbose" mode](https://github.com/josemmo/yamipa#configuration).

**Comment by Moxie15** [comment]
1.19.2 spigot MC and the newts protocoilib and ill try enable

**Comment by Moxie15** [comment]
i don't know what verbose and or how my stuff logged i have not touch that

**Comment by josemmo** [comment]
> 1.19.2 spigot MC and the newts protocoilib and ill try enable

What version of ProtocolLib are you using? Please give the version number, not just "the latest".

---

> i don't know what verbose and or how my stuff logged i have not touch that

You can enable Yamipa's verbose by modifying the "plugins/YamipaPlugin/config.yml" file as explain in [this link](https://github.com/josemmo/yamipa#configuration).

Without your server logs there's no way for me to debug the cause of the bug :/
You should be able to see those at your server's console or terminal.

**Comment by Moxie15** [comment]
[2022-10-13-1.log.txt](https://github.com/josemmo/yamipa/files/10438013/2022-10-13-1.log.txt)
[2022-10-13-2.log.txt](https://github.com/josemmo/yamipa/files/10438016/2022-10-13-2.log.txt)

**Comment by Moxie15** [comment]
[2022-12-26-1.log.txt](https://github.com/josemmo/yamipa/files/10438049/2022-12-26-1.log.txt)

**Comment by Moxie15** [comment]
sorry for the late replay
