### ISSUE TITLE
Command interfiring with the FastAsyncWorldEdit command

### ISSUE THREAD

**Issue by TonyMontero** [josemmo/yamipa#8]
The comand /image is exactly the same as FAWE, that makes unable to work since this plugin doesn't have alias as /yamipa:image

**Comment by josemmo** [comment]
Hi @TonyMontero,

Yamipa has two aliases for the `image` command: `yamipa` and `images`.
You can use any subcommand by replacing "/image" with one of those aliases.

**Comment by TonyMontero** [comment]
![image](https://user-images.githubusercontent.com/4236855/128057738-3de2b754-8742-4877-b02a-b2a179d0f5d0.png)
You sure?

**Comment by josemmo** [comment]
Well, yes, I'm pretty sure those are the aliases. 😁

If the "yamipa" alias is not loading then there has to be a bug in Yamipa or some sort of incompatibility issue with another plugins.

Things you can do to confirm it's a bug and not a server configuration issue:

- First, make sure you're running <ins>the latest Yamipa release</ins> ([v1.1.1](https://github.com/josemmo/yamipa/releases/tag/v1.1.1))
- Verify there's no stack trace in the <ins>server logs</ins> coming from Yamipa (easy to spot, it will contain the word "yamipa" somewhere)
- Verify the "/yamipa" alias is not been overwritten in <ins>[commands.yml](https://www.spigotmc.org/go/commands-yml)</ins>
- Verify you can run the "/yamipa" command <ins>from the server console</ins> (either that or make sure your player is OP / has been granted the permission `yamipa.*`).

Let me know if these steps solved the issue, otherwise it's a most surely a bug that needs to be fixed.

**Comment by TonyMontero** [comment]
Hey there!

- Using the lastest version
- Nothing on the server logs, it only shows that Yamipa is loading
- Nothing on the commands.yml also
- I can't even throw Yamipa from the server console, pretty weird 'cause I got it working upon I installed FastAsyncWorldEdit

**Comment by josemmo** [comment]
When running `yamipa` on the server console, instead of the help menu what error message do you get?
Also, if you OP your player can you run `/yamipa` from the game?

**Comment by TonyMontero** [comment]
After re-downloading the file again just in case it was corrupted and move the file to my full test server, now it recognizes the command but still doesn't want to work:

![image](https://user-images.githubusercontent.com/4236855/128075782-a14f8bb9-f48e-4193-881f-904736800352.png)
/yamipa subcommand won't work even with the autocompletion saying it's correct

Just says Unknown command. Type /help for help.

**Comment by josemmo** [comment]
@TonyMontero, please post a list of <ins>all plugins with version name</ins> you're using in the server where the bug occurs, the Bukkit/Spigot/PaperMC <ins>version of your server</ins> and any other configuration/log file you deem relevant.

**Comment by TonyMontero** [comment]
Hey there! 
My plugin list would have you killed (149), seems like the plugin making Yamipa not working is BetterFarming 3.4.2

**Comment by josemmo** [comment]
Well, that's unfortunate because BetterFarming is a paid plugin.

How do you know out of 149 plugins BetterFarming is the one causing this issue?

**Comment by TonyMontero** [comment]
Because I installed only Betterfarming, essentials and yamipa to see that isn't working

**Comment by TonyMontero** [comment]
If you feel better about it I can put the issue into BetterFarming's issue tracker to see if they can provide any kind of solution

**Comment by josemmo** [comment]
Does Yamipa work with just Essentials installed (and ProtocolLib)?

**Comment by TonyMontero** [comment]
I can't make it work with only ProtocolLib, Yamipa and BetterFarming

**Comment by josemmo** [comment]
Just to be sure I created a test server with CraftBukkit-1.17.1 / EssentialsX-2.18.2.0 / ProtocolLib-4.7.0 / YamipaPlugin-1.1.1, and although EssentialsX is incompatible with 1.17, it works, so at least we can discard that plugin.

---

> I can't make it work with only ProtocolLib, Yamipa and BetterFarming

In that case I'm afraid I cannot fix something I'm unable to reproduce. Being BetterFarming a paid plugin and without any additional logs nor information about your server (such as Minecraft server version) there's no way I can debug this.

You can try asking the BetterFarming developers, but if the thing that's not working is Yamipa they'll most surely tell you to create an issue in this repository (which makes sense).

**Comment by TonyMontero** [comment]
I'll ask to their developers then, thanks!
