### ISSUE TITLE
Towny Support Feature Request

### ISSUE THREAD

**Issue by ShermansWorld** [josemmo/yamipa#87]
Hello! I would like to start off by saying I think Yampia is an excellent plugin. I've found it easy to use, and overall it works much better than similar image map plugins.

With that said, I think you should consider adding Towny support, particularly so only players who have build permissions in a town will be able to break yamipa images. This has been a minor issue on my server, as I give custom images to players as rewards and other players are able to grief by breaking them.

**Comment by josemmo** [comment]
Hi @ShermansWorld,

Yamipa comes with a built-in permissions system. I assume with Towny you can grant custom permissions to only resident of a plot/town. If that's the case, check [this section](https://github.com/josemmo/yamipa#permissions) of the Yamipa documentation for more info.

If you want to use commands instead of items for placing images, Yamipa [is compatible](https://github.com/josemmo/yamipa#protecting-areas) with both WorldGuard and GriefPrevention. I guess support for Towny could be added, but honestly, I've tried reading through the [Javadoc](https://javadoc.jitpack.io/com/github/TownyAdvanced/Towny/0.98.4.0/javadoc/) of TownyAPI and I'm having trouble understanding what's the proper way of interacting with this plugin.

Do you know of what method to call for checking whether a player can place a block at a given coordinate?

**Comment by josemmo** [comment]
nvm, [found it](https://github.com/TownyAdvanced/Towny/wiki/TownyAPI#checking-if-a-player-can-builddestroy-somewhere)!

**Comment by josemmo** [comment]
@ShermansWorld, I've just added support for Towny. Try [v1.2.10-SNAPSHOT](https://github.com/josemmo/yamipa/releases/tag/v1.2.10-SNAPSHOT) and let me know if it works.

**Comment by ShermansWorld** [comment]
@josemmo, I've just tested it on my server and its working great. Thank you so much for adding this! Do you accept donations?

**Comment by josemmo** [comment]
Great! :)

Sure! You can donate at [this link](https://github.com/sponsors/josemmo?frequency=one-time).
